---
title: "Effets retardes et indice sur 3 ans"
author: "Agathe ROSENZWEIG"
date: "10/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Packages 
```{r}
library("haven")
library(tidyverse)
library(lubridate)
library(tictoc)
library(magrittr)
library(fixest)
library(lfe)
library("readxl")
library("writexl")
library(data.table)
library(dplyr)
library(xtable)
library(stargazer)
library(plm)
```

Import des données
```{r}
data_tvs <- read_csv("C:/Users/agros/Documents/GitHub/Project-DSSS/Données/base_finale_tvs_balanced.csv")
```


```{r}
#Avec un lag de 1 
data_tvs %<>% group_by(code_tvs) %>% mutate(densite_4 = lag(densite, 4))
lag_1 <- plm(age_moyen_deces ~ densite_4 + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                    NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                    CSagriculteurs + CSretraites + Fpop_tot + X15_29 + X30_44 + X45_59 + X60_74 + plus75 + as.factor(annee) - 1,
                  data = data_tvs, index = c("code_tvs","annee"), model = "within")

summary(lag_1)
lag_2 <- plm(log_morts ~ densite_1 + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                    NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                    CSagriculteurs + CSretraites + Fpop_tot + X15_29 + X30_44 + X45_59 + X60_74 + plus75 + as.factor(annee) - 1,
                  data = data_tvs, index = c("code_tvs","annee"), model = "within")


#Avec un pas de 3 ans
table(data_tvs$annee)
data_tvs$laps <- ifelse(data_tvs$annee %in% (2006:2009), "2006-2009", ifelse(data_tvs$annee %in% (2010:2012), "2010-2012", ifelse(data_tvs$annee %in% (2013:2015), "2013-2015", "2016-2018")))

table(data_tvs$laps)

laps_1 <- plm(age_moyen_deces ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                    NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                    CSagriculteurs + CSretraites + Fpop_tot + X15_29 + X30_44 + X45_59 + X60_74 + plus75 + as.factor(laps) - 1,
                  data = data_tvs, index = c("code_tvs","annee"), model = "within")


laps_2 <- plm(log_morts ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                    NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                    CSagriculteurs + CSretraites + Fpop_tot + X15_29 + X30_44 + X45_59 + X60_74 + plus75 + as.factor(laps) - 1,
                  data = data_tvs, index = c("code_tvs","annee"), model = "within")




# Latex output
stargazer(lag_1, laps_1, lag_2, laps_2,  title="Results", align=TRUE, keep = "densite")

```

