---
title: "Projet de DSSS"
author: "Agathe ROSENZWEIG"
date: "14/02/2022"
output: html_document

---


```{r}
library(readr)
library(dplyr)
library(xtable)
library(stats)
```


Importation des bases
```{r}
#répertoires
mortalite_path <- "C:/Users/agros/Documents/3AMIE/Project in Data Science and Social Science/Project in DSSS"

#décès

files_list <- list.files(sprintf('%s', mortalite_path), pattern = 'deces-201[0-9]+.txt', full.names = T)

positions <- c(
  nom = 80,
  sexe = 1,
  naissance_date = 8,
  naissance_code_lieu = 5,
  naissance_commune = 30,
  naissance_pays = 30,
  deces_date = 8,
  deces_code_lieu = 5,
  deces_numero_acte = 9
)

deces <- lapply(files_list, read_fwf,
                        col_positions = fwf_widths(positions, col_names = names(positions)),
                        col_types = cols(
                          .default = col_character())
)
```



Data cleaning
```{r}
# Attention pour les dates : certaines sont approximatives. Lorsque c'est le cas
# la partie incertaine (mois ou jour) est 00 -> remplacer les 00 par 01.
# Pour les années inconnues -> ne rien mettre ?

#transforme dates en numériques
nettoyer_partie_date <- function(
  x,
  debut,
  fin
) {
  rez <- x %>%
    substr(debut, fin) %>% 
    as.integer()
  
  rez[rez==0] <- NA
  rez
}

#impute moyenne
complete_manquant <- function(x) {
  x[is.na(x)] <- as.integer(mean(x, na.rm = TRUE))
  x
}

#applique ces 2 fonctions aux colonnes dates
clean_date <- function(df){
  clean_df <- df %>%
    mutate(
      naissance_annee = nettoyer_partie_date(naissance_date, 1, 4),
      naissance_annee_complete = complete_manquant(naissance_annee), 
      naissance_mois = nettoyer_partie_date(naissance_date, 5, 6),
      naissance_mois_complete = complete_manquant(naissance_mois), 
      naissance_jour = nettoyer_partie_date(naissance_date, 7, 8),
      naissance_jour_complete = complete_manquant(naissance_jour), 
      naissance_date_brute = naissance_date,
      naissance_date = as.Date(naissance_date, '%Y%m%d'),
      naissance_date_complete = as.Date(paste0(naissance_annee_complete, '-', naissance_mois_complete, '-', naissance_jour_complete)),
      deces_annee = nettoyer_partie_date(deces_date, 1, 4),
      deces_annee_complete = complete_manquant(deces_annee), 
      deces_mois = nettoyer_partie_date(deces_date, 5, 6),
      deces_mois_complete = complete_manquant(deces_mois), 
      deces_jour = nettoyer_partie_date(deces_date, 7, 8),
      deces_jour_complete = complete_manquant(deces_jour), 
      deces_date = as.Date(deces_date, '%Y%m%d'),
      deces_date_complete = as.Date(paste0(deces_annee_complete, '-', deces_mois_complete, '-', deces_jour_complete))
    ) %>%
    select(nom, sexe, naissance_date_brute,naissance_date_complete, naissance_code_lieu,
           naissance_commune, naissance_pays, deces_date, deces_date_complete, deces_code_lieu,
           deces_numero_acte)
  clean_df
}



deces <- lapply(deces, clean_date)

deces_15_19 <- bind_rows(deces) %>% distinct(.keep_all = T)

A <- deces_15_19 %>% group_by(deces_code_lieu) %>% summarise(n = n())

any(is.na(deces_15_19$naissance_date_complete))
any(is.na(deces_15_19$deces_date_complete))
```


Variable d'intérêt à l'échelle de l'individu
```{r}
#On crée la variable qui comptabilise le nombre de semaines en vie
deces_15_19 <- deces_15_19 %>% mutate(age = round(as.numeric((deces_date_complete - naissance_date_complete)/365),1))

print(summary(deces_15_19$age))

deces_15_19$annee_mort <- format(deces_15_19$deces_date, format="%Y")

L <- rbind(summary(filter(deces_15_19, annee_mort == "2015")$age),
summary(filter(deces_15_19, annee_mort == "2016")$age),
summary(filter(deces_15_19, annee_mort == "2017")$age),
summary(filter(deces_15_19, annee_mort == "2018")$age),
summary(filter(deces_15_19, annee_mort == "2019")$age))

rownames(L) <- (2015:2019)
xtable(L)


```



Base à l'échelle des communes
```{r}
libelle <- read.csv("commune2021.csv", sep = ",")[, c("COM", "NCC", "DEP")]

base_com <- deces_15_19 %>%
  group_by(deces_code_lieu, annee_mort) %>%
  summarise_at(vars(age), list(age = mean))

base_com <- merge(base_com, deces_15_19 %>%
  group_by(deces_code_lieu, annee_mort)  %>% 
  summarise(nombre_deces = n()), by = c("deces_code_lieu", "annee_mort"))

base_com <- merge(libelle, base_com, by.x = "COM", by.y = "deces_code_lieu")

base_com
```



Base à l'échelle du département pour viz
```{r}
library(raster)

base_dep <- base_com  %>%
  group_by(DEP , annee_mort) %>%
  summarise_at(vars(age), list(age = mean))

base_dep <- merge(base_dep, base_com  %>%
  group_by(DEP , annee_mort) %>%
  summarise_at(vars(nombre_deces), list(nombre_deces = sum)), by = c("DEP", "annee_mort"))


base_dep <- base_dep[base_dep$DEP != "",]

write.csv(base_dep, "base_dep.csv")


FranceFormes <- getData('GADM', country='FRA', level=2)


plot_fr <- function(annee){
 idx <- match(FranceFormes$CC_2, filter(base_dep, annee_mort == annee)$DEP)
concordance <- filter(base_dep, annee_mort == annee)[idx, "age"]
FranceFormes$age<- concordance
couleurs <- colorRampPalette(c('grey', 'blue'))

spplot(FranceFormes, "age",col.regions=couleurs(30),  main=list(label= paste0("Nombre total d'années vécues en ", annee),cex=.8)) 
}

plot_fr("2015")
plot_fr("2016")
plot_fr("2017")
plot_fr("2018")
plot_fr("2019")


```

Problème avec le département de l'OISE (60)
```{r}
filter(base_dep, DEP == "60")
```



Max et min à l'échelle du département
```{r}
xtable(rbind(filter(base_dep, annee_mort == "2015")[filter(base_dep, annee_mort == "2015")$age == max(filter(base_dep, annee_mort == "2015")$age),],
filter(base_dep, annee_mort == "2016")[filter(base_dep, annee_mort == "2016")$age == max(filter(base_dep, annee_mort == "2016")$age),],
filter(base_dep, annee_mort == "2017")[filter(base_dep, annee_mort == "2017")$age == max(filter(base_dep, annee_mort == "2017")$age),],
filter(base_dep, annee_mort == "2018")[filter(base_dep, annee_mort == "2018")$age == max(filter(base_dep, annee_mort == "2018")$age),],
filter(base_dep, annee_mort == "2019")[filter(base_dep, annee_mort == "2019")$age == max(filter(base_dep, annee_mort == "2019")$age),]))
```

```{r}
library("ggplot2")
ggplot(deces_15_19, aes(x=age)) + 
  geom_density()
quantile(deces_15_19$age, probs = c(0,0.01,0.25,0.5,0.75,0.9,0.99,0.999))
```

Mortalité infantile
```{r}
nrow(deces_15_19 %>% filter(age == 0))
```

par sexe: résultats cohérents
```{r}
deces_15_19 %>% group_by(sexe) %>% summarise(age_moyen = mean(age))
```


par département (Représentation Mathieu)
```{r}
table_passage <- read_excel("~/ENSAE/3A/Projet_DSSS/table-appartenance-geo-communes-21.xlsx", sheet = "COM", skip = 5)
table_passage %<>% select(CODGEO, LIBGEO, DEP)


deces_15_19 %<>% filter(!is.na(deces_code_lieu)) %>%
  left_join(table_passage, by = c('deces_code_lieu' = 'CODGEO')) %>%
  mutate(annee_deces = year(deces_date_complete))

A <- deces_15_19 %>% group_by(annee_deces, DEP) %>% summarise(n = n(), age = mean(age)) %>%
  filter(annee_deces > 2014) %>%
  arrange(age, .by_group = T)

```




Corrélation avec APL
```{r}
apl <- read.csv("Project in DSSS/base_APL_complete.csv", sep = ",")

correlation <- function(annee){
  base_totale <- merge(filter(base_com, annee_mort == annee), apl[, c("commune_code", paste0("APL_med_gen_", annee))], by.x = "COM", by.y = "commune_code")
  return(cor.test(base_totale$age, base_totale[,paste0("APL_med_gen_", annee)]))
}

correlation("2015")
correlation("2016")
correlation("2017")
correlation("2018")
correlation("2019")
```

```{r}
apl_dep <- aggregate(apl, list(apl$dep), mean)
apl_dep
apl_dep <- filter(apl_dep, Group.1!= "971" & Group.1!= "972" & Group.1!= "973" & Group.1!= "974" & Group.1!= "" & is.na(apl_dep$Group.1) == FALSE)

nrow(apl_dep)

plot_fr_apl <- function(annee){
 idx <- match(FranceFormes$CC_2,apl_dep$Group.1)
concordance <-apl_dep[idx, paste0("APL_med_gen_", annee)]
FranceFormes$APL_med_gen <- concordance

couleurs <- colorRampPalette(c('grey', 'darkblue'))

spplot(FranceFormes, "APL_med_gen",col.regions=couleurs(30),  main=list(label= paste0("Nombre total d'années vécues en ", annee),cex=.8)) 
}

plot_fr_apl("2015")
plot_fr_apl("2016")
plot_fr_apl("2017")
plot_fr_apl("2018")
plot_fr_apl("2019")
```



Equipements
```{r}
data <- read_csv2(file.choose())
A <- data %>% distinct(UU2020, .keep_all = T)
A <- data %>% filter(TYPEQU == "D201")
```
```

