---
title: "Dernières régressions - suite de Mathieu"
output: html_notebook
---
Base en entrée : base_finale_tvs.csv (après analyses de Mathieu)



```{r}
library("haven")
library(tidyverse)
library(lubridate)
library(tictoc)
library(magrittr)
library(fixest)
library(lfe)
library("readxl")
library("writexl")
library(data.table)
library(imputeTS)
library(dplyr)
library(xtable)
```


Import des données 
```{r}
data_tvs <- read_csv("C:/Users/agros/Documents/GitHub/Project-DSSS/Données/base_finale_tvs.csv")
```

Filtre 2006 - 2018
```{r}
data_tvs %<>% filter(annee >= 2006 & annee < 2019)

unique((data_tvs %>% filter(pop_tot <= 1000))$libelle_tvs)
#On part de 2727 tvs pour lesquels on dispose de toutes les informations nécessaires 
data_tvs <- data_tvs %>% filter(pop_tot >= 1000)


data_tvs %<>% mutate(densite = 1000*nb_medecins/pop_tot, log_pop = log(pop_tot),
         log_morts = if_else(nb_morts==0, 0, log(nb_morts)),
         log_morts_jeunes = if_else(nb_morts_jeunes==0, 0, log(nb_morts_jeunes)),
         log_morts_vieux = if_else(nb_morts_vieux==0, 0, log(nb_morts_vieux)),
         part_jeunes = nb_morts_jeunes/nb_morts,
         part_vieux = nb_morts_vieux/nb_morts,
         taille_menage = pop_tot/nb_menages_tot)

table(is.na(data_tvs$densite))
table(is.na(data_tvs$nb_medecins))
#On ne dispose pas de la densite et du nb de medecins pour 64 observations
length(table(filter(data_tvs, is.na(data_tvs$densite))$code_tvs))
#Ce qui correspond à 16 TVS (les 16 arrondissements de Marseille, pour les années 2006 à 2009 )

```


```{r}
data_tvs %<>% mutate(tranche_deces = ifelse(age_moyen_deces <= 75, "Inf 75", ifelse(age_moyen_deces <= 80, "75-80", ifelse(age_moyen_deces <= 85, "80-85", "Sup 85"))))


tableau_freq <- t(data_tvs %>%
  group_by(tranche_deces) %>%
  summarise_at(vars(densite, log_pop, taille_menage, med_niveau_vie, NB_D401, NB_D106, NB_D101, NB_D102, NB_D103, NB_D104, NB_D105, CSprof_interm, CScadres, CSemployes, CSouvriers,  CSartisans_commercants, CSagriculteurs, CSretraites, F30_44, F45_59, F60_74, Fplus75, Fpop_tot, `15_29`, `30_44`, `45_59`, `60_74`, plus75, F15_29), funs(mean(., na.rm=TRUE))))

tableau_freq <- tableau_freq[, -c(5)]

tableau_freq <- rbind(tableau_freq, table(data_tvs$tranche_deces))[-c(1), ]

rownames(tableau_freq) <- c('Densité médicale', 'Log(population)', 'Taille moyenne des ménages', 'Mediane du niveau de vie', "Etablissement d'hébergement pour personnes âgées", "Service d'urgences", " Etablissement santé court séjour", "Etablissement santé moyen séjour", "Etablissement santé long séjour", "Etablissement psychiatrique", "Centre Lutte Cancer", "Proportion de professions intermédiaires", "Proportion de cadres", "Proportion d'employés", "Proportion d'ouvriers", "Proportion d'artisans commerçants", "Proportion d'agriculteurs", "Proportion de retraités", "Femmes 30-44 ans", "Femmes 45-59 ans", "Femmes 60-74 ans", "Femmes +75 ans", "Femmes proportion totale", "15-29 ans", "30-44 ans", "45-59 ans", "69-74 ans", "+ 75 ans", "Femmes 15-29 ans", "N")


tableau_freq <- tableau_freq[, c("Inf 75", "75-80", "80-85", "Sup 85")]
tableau_freq
xtable(tableau_freq)
```

Corrplot pour s'assurer que la variable "densite" ne soit pas trop corrélée aux autres variables de contrôle
```{r}
library(corrplot)
M<-cor(filter(data_tvs, annee == "2008")[, c("age_moyen_deces", "log_morts","densite", "log_pop", "taille_menage", "med_niveau_vie", "NB_D401", "NB_D106", "NB_D101", "NB_D102", "NB_D103", "NB_D104", "NB_D105", "CSprof_interm", "CScadres", "CSemployes", "CSouvriers",  "CSartisans_commercants", "CSagriculteurs", "CSretraites", "Fpop_tot", "15_29", "30_44", "45_59", "60_74", "plus75")], use="complete.obs")
corrplot(M, type="upper", tl.col="black", tl.srt=90, tl.cex = 0.6)

```

Export des statistiques descriptives de la population par TVS (Stats en annexe)
```{r}
L <- numeric(6)
for (year in unique(data_tvs$annee)){
  L <- rbind(L, summary(filter(data_tvs, annee == year)$pop_tot))
}
rownames(L) <- c(0, (2006:2018))
xtable(L, digits = 0)
```



Spécification de base 
```{r}
library(fixest)


formula <- as.formula(age_moyen_deces ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                 NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                 CSagriculteurs + CSretraites + Fpop_tot + `15_29` +
                 `30_44` + `45_59` + `60_74` + plus75 + as.factor(annee)
                 | code_tvs)

#Specification base_line
fixed_1 <- feols(formula, data=data_tvs %>% filter(!is.na(taille_menage)))

#focus sur les communes sous dense
fixed_2 <- feols(formula, data= data_tvs %>% mutate(sous_dense = if_else(densite <= quantile(A$densite, probs = c(0.25)), 1, 0)) %>%
  group_by(code_tvs) %>% mutate(sous_dense = max(sous_dense)) %>%
  filter(sous_dense == 1))

#focus sur les communes les moins peuplées 
fixed_3 <- feols(formula, data=data_tvs %>% mutate(sous_dense = if_else(pop_tot <= quantile(A$pop_tot, probs = c(0.25)), 1, 0)) %>%
  group_by(code_tvs) %>% mutate(sous_dense = max(sous_dense)) %>%
  filter(sous_dense == 1)
)


#focus sur les communes où la part de retraités est la plus grande 
fixed_4 <- feols(formula, data=
B <- data_tvs %>% mutate(sous_dense = if_else(CSretraites >= quantile(A$CSretraites, probs = c(0.75)), 1, 0)) %>%
  group_by(code_tvs) %>% mutate(sous_dense = max(sous_dense)) %>%
  filter(sous_dense == 1)
)


# Latex output
etable(list(fixed_1, fixed_2, fixed_4), tex=TRUE, keep = "densite")


#Output pour annexes
etable(list(fixed_1), tex=TRUE,dict=c("log_pop" = "Log(population)", "taille_menage" = "Taille des ménages", "med_niveau_vie" = "Médiane du niveau de vie", "NB_D401" = "Hébergements pour personnes âgées", "NB_D106" = "Services d'Urgences", "NB_D104" = "Etablissements psychiatriques", "NB_D101" = "Etablissements de santé court séjour", "NB_D102" = "Etablissements de santé moyen séjour", "NB_D103" = "Etablissements de santé long séjour", "CScadres" = "Proportion de cadres", "CSemployes" = "Proportion d'employés", "CSouvriers" = "Proportion d'ouvriers", "CSagriculteurs" = "Proportion d'agriculteurs", "CSartisans_commercants"= "Proportion d'artisans-commerçants", "CSretraites" = "Proportion de retraités", "Fpop_tot" = "Proportion de femmes", "`15_29`" = "Proportion de 15-29 ans", "`30_44`" = "Proportion de 30-44 ans", "`45_59`" = "Proportion de 45-59 ans", "`60_74`" = "Proportion de 60-74 ans", "plus75" = "Proportion de plus de 75 ans", "as.factor(annee)2007" = "2007","as.factor(annee)2008" = "2008", "as.factor(annee)2009" = "2009", "as.factor(annee)2010" = "2010", "as.factor(annee)2011" = "2011", "as.factor(annee)2012" = "2012", "as.factor(annee)2013" = "2013", "as.factor(annee)2014" = "2014", "as.factor(annee)2015" = "2015", "as.factor(annee)2016" = "2016", "as.factor(annee)2017" = "2017","as.factor(annee)2018" = "2018", "NB_D105" = "Centres de Lutte contre le Cancer"))
```


Autres spécifications 
```{r}

formula <- as.formula(log_morts ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                 NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                 CSagriculteurs + CSretraites + Fpop_tot + `15_29` +
                 `30_44` + `45_59` + `60_74` + plus75 + as.factor(annee)
                 | code_tvs)

#Specification base_line
fixed_1 <- feols(formula, data=data_tvs %>% filter(!is.na(taille_menage)))

#focus sur les communes sous dense
fixed_2 <- feols(log_morts_jeunes ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                 NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                 CSagriculteurs + CSretraites + Fpop_tot + `15_29` +
                 `30_44` + `45_59` + `60_74` + plus75 + as.factor(annee)
                 | code_tvs, data=data_tvs %>% filter(!is.na(taille_menage)))


fixed_3 <- feols(log_morts_vieux ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                 NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                 CSagriculteurs + CSretraites + Fpop_tot + `15_29` +
                 `30_44` + `45_59` + `60_74` + plus75 + as.factor(annee)
                 | code_tvs, data=data_tvs %>% filter(!is.na(taille_menage)))



fixed_4<- feols(part_jeunes ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                 NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                 CSagriculteurs + CSretraites + Fpop_tot + `15_29` +
                 `30_44` + `45_59` + `60_74` + plus75 + as.factor(annee)
                 | code_tvs, data=data_tvs %>% filter(!is.na(taille_menage)))

fixed_5 <- feols(part_vieux ~ densite + log_pop + taille_menage + med_niveau_vie + NB_D401 + NB_D106 +
                 NB_D101 + NB_D102 + NB_D103 + NB_D104 + NB_D105 + CSprof_interm + CScadres + CSemployes + CSouvriers + CSartisans_commercants +
                 CSagriculteurs + CSretraites + Fpop_tot + `15_29` +
                 `30_44` + `45_59` + `60_74` + plus75 + as.factor(annee)
                 | code_tvs, data=data_tvs %>% filter(!is.na(taille_menage)))

# Latex output
etable(list(fixed_1, fixed_2, fixed_3, fixed_4, fixed_5), tex=TRUE, keep = "densite")
```


#decomposition variance
```{r}
data_tvs1 <- data_tvs %>% filter(!is.na(age_moyen_deces) & !is.na(densite) & !is.na(nb_morts)) %>%
  mutate(nb_morts_hab = nb_morts/pop_tot) %>%
  mutate(moy_age = mean(age_moyen_deces),
         moy_nb_morts = mean(nb_morts_hab),
         moy_densite = mean(densite))

nb_tvs <- n_distinct(data_tvs1$code_tvs)

print(c("Nombre de lignes sans NA", n))

data_tvs1 %<>% group_by(code_tvs) %>% mutate(moy_age_tvs = mean(age_moyen_deces),
                                             moy_nb_morts_tvs = mean(nb_morts_hab),
                                             moy_densite_tvs = mean(densite)) %>%
  mutate(ecart_age_with = age_moyen_deces - moy_age_tvs,
         ecart_nb_morts_with = nb_morts_hab - moy_nb_morts_tvs,
         ecart_densite_with = densite - moy_densite_tvs) %>%
  ungroup()


overall_var_age_deces <- var(data_tvs1$age_moyen_deces)
overall_var_nb_morts <- var(data_tvs1$nb_morts_hab)
overall_var_densite <- var(data_tvs1$densite)

between_var <- data_tvs1 %>% distinct(code_tvs, .keep_all = T) %>%
  mutate(ecart_age_betw = moy_age_tvs - moy_age,
         ecart_nb_morts_betw = moy_nb_morts_tvs - moy_nb_morts,
         ecart_densite_betw = moy_densite_tvs - moy_densite)
between_var_age_deces <- sum((between_var$ecart_age_betw)^2)/nb_tvs
between_var_nb_morts <- sum((between_var$ecart_nb_morts_betw)^2)/nb_tvs
between_var_densite <- sum((between_var$ecart_densite_betw)^2)/nb_tvs

within_var_age_deces <- sum((data_tvs1$ecart_age_with)^2)/(n-1)
within_var_nb_morts <- sum((data_tvs1$ecart_nb_morts_with)^2)/(n-1)
within_var_densite <- sum((data_tvs1$ecart_densite_with)^2)/(n-1)

var <- data.frame(Variable = c("age_moyen_deces", "Nb_morts_hab", "densite"),
                  Overall = c(overall_var_age_deces, overall_var_nb_morts, overall_var_densite),
                  Between = c(between_var_age_deces, between_var_nb_morts, between_var_densite),
                  Within = c(within_var_age_deces, within_var_nb_morts, within_var_densite))
var %<>% mutate(Part_within = Within/Overall)
xtable(var, digits = 3)
```

